package gui;

import algorithms.AStar;
import algorithms.BreadthFirstSearch;
import algorithms.DepthFirstSearch;
import javax.swing.JOptionPane;
import puzzle.Problem;

/**
 *
 * @author eduardo
 */
public class Main extends javax.swing.JFrame {

    private byte puzzleSize = 3;
    private byte[][] puzzle;
    
    /**
     * Creates new form main
     */
    public Main() {
        initComponents();
        jButtonSearch.setText("Search "+algorithmsGroup.getSelection().getActionCommand()+" !");
    }//end main

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        algorithmsGroup = new javax.swing.ButtonGroup();
        puzzleSizeGroup = new javax.swing.ButtonGroup();
        jPanel_container = new javax.swing.JPanel();
        jPanel_puzzle = new javax.swing.JPanel();
        jPanel_3by3Puzzle = new javax.swing.JPanel();
        jTextField_3tile_0 = new javax.swing.JTextField();
        jTextField_3tile_1 = new javax.swing.JTextField();
        jTextField_3tile_2 = new javax.swing.JTextField();
        jTextField_3tile_3 = new javax.swing.JTextField();
        jTextField_3tile_4 = new javax.swing.JTextField();
        jTextField_3tile_5 = new javax.swing.JTextField();
        jTextField_3tile_6 = new javax.swing.JTextField();
        jTextField_3tile_7 = new javax.swing.JTextField();
        jTextField_3tile_8 = new javax.swing.JTextField();
        jPanel_4by4Puzzle = new javax.swing.JPanel();
        jTextField_4tile_0 = new javax.swing.JTextField();
        jTextField_4tile_1 = new javax.swing.JTextField();
        jTextField_4tile_2 = new javax.swing.JTextField();
        jTextField_4tile_3 = new javax.swing.JTextField();
        jTextField_4tile_4 = new javax.swing.JTextField();
        jTextField_4tile_5 = new javax.swing.JTextField();
        jTextField_4tile_6 = new javax.swing.JTextField();
        jTextField_4tile_7 = new javax.swing.JTextField();
        jTextField_4tile_8 = new javax.swing.JTextField();
        jTextField_4tile_9 = new javax.swing.JTextField();
        jTextField_4tile_10 = new javax.swing.JTextField();
        jTextField_4tile_11 = new javax.swing.JTextField();
        jTextField_4tile_12 = new javax.swing.JTextField();
        jTextField_4tile_13 = new javax.swing.JTextField();
        jTextField_4tile_14 = new javax.swing.JTextField();
        jTextField_4tile_15 = new javax.swing.JTextField();
        jPanel_info = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInfo = new javax.swing.JTextArea();
        jButtonSearch = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_settings = new javax.swing.JMenu();
        jMenu_configureAlgorithm = new javax.swing.JMenu();
        jRadioButtonMenuItem_BFS = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_DFS = new javax.swing.JRadioButtonMenuItem();
        jMenu_AStar = new javax.swing.JMenu();
        jRadioButtonMenuItem_manhattanDistance = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_missplacedTiles = new javax.swing.JRadioButtonMenuItem();
        jMenu_puzzleSize = new javax.swing.JMenu();
        jRadioButtonMenuItem_3by3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem_4by4 = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel_puzzle.setLayout(new java.awt.CardLayout());

        jTextField_3tile_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_3tile_0.setText("Tile");
        jTextField_3tile_0.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField_3tile_0.setSize(new java.awt.Dimension(70, 70));

        jTextField_3tile_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_3tile_1.setText("Tile");
        jTextField_3tile_1.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField_3tile_1.setSize(new java.awt.Dimension(70, 70));

        jTextField_3tile_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_3tile_2.setText("Tile");
        jTextField_3tile_2.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField_3tile_2.setSize(new java.awt.Dimension(70, 70));

        jTextField_3tile_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_3tile_3.setText("Tile");
        jTextField_3tile_3.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField_3tile_3.setSize(new java.awt.Dimension(70, 70));

        jTextField_3tile_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_3tile_4.setText("Tile");
        jTextField_3tile_4.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField_3tile_4.setSize(new java.awt.Dimension(70, 70));

        jTextField_3tile_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_3tile_5.setText("Tile");
        jTextField_3tile_5.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField_3tile_5.setSize(new java.awt.Dimension(70, 70));

        jTextField_3tile_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_3tile_6.setText("Tile");
        jTextField_3tile_6.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField_3tile_6.setSize(new java.awt.Dimension(70, 70));

        jTextField_3tile_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_3tile_7.setText("Tile");
        jTextField_3tile_7.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField_3tile_7.setSize(new java.awt.Dimension(70, 70));

        jTextField_3tile_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_3tile_8.setText("Tile");
        jTextField_3tile_8.setPreferredSize(new java.awt.Dimension(70, 70));
        jTextField_3tile_8.setSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout jPanel_3by3PuzzleLayout = new javax.swing.GroupLayout(jPanel_3by3Puzzle);
        jPanel_3by3Puzzle.setLayout(jPanel_3by3PuzzleLayout);
        jPanel_3by3PuzzleLayout.setHorizontalGroup(
            jPanel_3by3PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_3by3PuzzleLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel_3by3PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_3by3PuzzleLayout.createSequentialGroup()
                        .addComponent(jTextField_3tile_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_3tile_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_3tile_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_3by3PuzzleLayout.createSequentialGroup()
                        .addComponent(jTextField_3tile_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_3tile_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_3tile_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_3by3PuzzleLayout.createSequentialGroup()
                        .addComponent(jTextField_3tile_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_3tile_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_3tile_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel_3by3PuzzleLayout.setVerticalGroup(
            jPanel_3by3PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_3by3PuzzleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_3by3PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_3tile_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_3tile_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_3tile_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_3by3PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_3tile_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_3tile_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_3tile_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_3by3PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_3tile_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_3tile_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_3tile_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel_puzzle.add(jPanel_3by3Puzzle, "3 by 3");

        jTextField_4tile_0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_0.setText("Tile");
        jTextField_4tile_0.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_0.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_1.setText("Tile");
        jTextField_4tile_1.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_1.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_2.setText("Tile");
        jTextField_4tile_2.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_2.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_3.setText("Tile");
        jTextField_4tile_3.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_3.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_4.setText("Tile");
        jTextField_4tile_4.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_4.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_5.setText("Tile");
        jTextField_4tile_5.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_5.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_6.setText("Tile");
        jTextField_4tile_6.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_6.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_7.setText("Tile");
        jTextField_4tile_7.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_7.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_8.setText("Tile");
        jTextField_4tile_8.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_8.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_9.setText("Tile");
        jTextField_4tile_9.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_9.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_10.setText("Tile");
        jTextField_4tile_10.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_10.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_11.setText("Tile");
        jTextField_4tile_11.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_11.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_12.setText("Tile");
        jTextField_4tile_12.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_12.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_13.setText("Tile");
        jTextField_4tile_13.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_13.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_14.setText("Tile");
        jTextField_4tile_14.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_14.setSize(new java.awt.Dimension(60, 60));

        jTextField_4tile_15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_4tile_15.setText("Tile");
        jTextField_4tile_15.setPreferredSize(new java.awt.Dimension(60, 60));
        jTextField_4tile_15.setSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel_4by4PuzzleLayout = new javax.swing.GroupLayout(jPanel_4by4Puzzle);
        jPanel_4by4Puzzle.setLayout(jPanel_4by4PuzzleLayout);
        jPanel_4by4PuzzleLayout.setHorizontalGroup(
            jPanel_4by4PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_4by4PuzzleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_4by4PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_4by4PuzzleLayout.createSequentialGroup()
                        .addComponent(jTextField_4tile_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_4tile_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_4tile_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_4tile_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_4by4PuzzleLayout.createSequentialGroup()
                        .addComponent(jTextField_4tile_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_4tile_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_4tile_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_4tile_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_4by4PuzzleLayout.createSequentialGroup()
                        .addComponent(jTextField_4tile_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_4tile_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_4tile_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_4tile_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_4by4PuzzleLayout.createSequentialGroup()
                        .addComponent(jTextField_4tile_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_4tile_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_4tile_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_4tile_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel_4by4PuzzleLayout.setVerticalGroup(
            jPanel_4by4PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_4by4PuzzleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_4by4PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_4tile_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_4tile_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_4tile_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_4tile_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_4by4PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_4tile_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_4tile_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_4tile_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_4tile_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_4by4PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_4tile_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_4tile_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_4tile_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_4tile_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_4by4PuzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_4tile_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_4tile_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_4tile_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_4tile_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel_puzzle.add(jPanel_4by4Puzzle, "4 by 4");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextAreaInfo.setEditable(false);
        jTextAreaInfo.setColumns(20);
        jTextAreaInfo.setLineWrap(true);
        jTextAreaInfo.setRows(5);
        jTextAreaInfo.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaInfo);
        jTextAreaInfo.getAccessibleContext().setAccessibleName("");

        jButtonSearch.setText("Search !");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_infoLayout = new javax.swing.GroupLayout(jPanel_info);
        jPanel_info.setLayout(jPanel_infoLayout);
        jPanel_infoLayout.setHorizontalGroup(
            jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButtonSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_infoLayout.setVerticalGroup(
            jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearch)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_containerLayout = new javax.swing.GroupLayout(jPanel_container);
        jPanel_container.setLayout(jPanel_containerLayout);
        jPanel_containerLayout.setHorizontalGroup(
            jPanel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_puzzle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_containerLayout.setVerticalGroup(
            jPanel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_containerLayout.createSequentialGroup()
                        .addComponent(jPanel_puzzle, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu_settings.setText("Settings");

        jMenu_configureAlgorithm.setText("Search Algorithm");

        algorithmsGroup.add(jRadioButtonMenuItem_BFS);
        jRadioButtonMenuItem_BFS.setSelected(true);
        jRadioButtonMenuItem_BFS.setText("Breadth First Search");
        jRadioButtonMenuItem_BFS.setActionCommand("BFS");
        jRadioButtonMenuItem_BFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem_BFSActionPerformed(evt);
            }
        });
        jMenu_configureAlgorithm.add(jRadioButtonMenuItem_BFS);

        algorithmsGroup.add(jRadioButtonMenuItem_DFS);
        jRadioButtonMenuItem_DFS.setText("Depth First Search");
        jRadioButtonMenuItem_DFS.setActionCommand("DFS");
        jRadioButtonMenuItem_DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem_DFSActionPerformed(evt);
            }
        });
        jMenu_configureAlgorithm.add(jRadioButtonMenuItem_DFS);

        jMenu_AStar.setText("A*");

        algorithmsGroup.add(jRadioButtonMenuItem_manhattanDistance);
        jRadioButtonMenuItem_manhattanDistance.setText("Manhattan Distance Heuristic");
        jRadioButtonMenuItem_manhattanDistance.setActionCommand("A* Manhattan");
        jRadioButtonMenuItem_manhattanDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem_manhattanDistanceActionPerformed(evt);
            }
        });
        jMenu_AStar.add(jRadioButtonMenuItem_manhattanDistance);

        algorithmsGroup.add(jRadioButtonMenuItem_missplacedTiles);
        jRadioButtonMenuItem_missplacedTiles.setText("Missplaced Tiles Heuristic");
        jRadioButtonMenuItem_missplacedTiles.setActionCommand("A* Missplaced");
        jRadioButtonMenuItem_missplacedTiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem_missplacedTilesActionPerformed(evt);
            }
        });
        jMenu_AStar.add(jRadioButtonMenuItem_missplacedTiles);

        jMenu_configureAlgorithm.add(jMenu_AStar);

        jMenu_settings.add(jMenu_configureAlgorithm);

        jMenu_puzzleSize.setText("Puzzle Size");

        puzzleSizeGroup.add(jRadioButtonMenuItem_3by3);
        jRadioButtonMenuItem_3by3.setSelected(true);
        jRadioButtonMenuItem_3by3.setText("3 x 3");
        jRadioButtonMenuItem_3by3.setActionCommand("3");
        jRadioButtonMenuItem_3by3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem_3by3ActionPerformed(evt);
            }
        });
        jMenu_puzzleSize.add(jRadioButtonMenuItem_3by3);

        puzzleSizeGroup.add(jRadioButtonMenuItem_4by4);
        jRadioButtonMenuItem_4by4.setText("4 x 4");
        jRadioButtonMenuItem_4by4.setActionCommand("4");
        jRadioButtonMenuItem_4by4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem_4by4ActionPerformed(evt);
            }
        });
        jMenu_puzzleSize.add(jRadioButtonMenuItem_4by4);

        jMenu_settings.add(jMenu_puzzleSize);
        jMenu_settings.add(jSeparator1);

        jMenuItem_about.setText("About");
        jMenuItem_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_aboutActionPerformed(evt);
            }
        });
        jMenu_settings.add(jMenuItem_about);

        jMenuBar1.add(jMenu_settings);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMenuItem_DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem_DFSActionPerformed
        jButtonSearch.setText("Search "+algorithmsGroup.getSelection().getActionCommand()+" !");
    }//GEN-LAST:event_jRadioButtonMenuItem_DFSActionPerformed
    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        String selectedAlgorithm = algorithmsGroup.getSelection().getActionCommand();
        jTextAreaInfo.setText("");
        
        try {
            generatePuzzle();
            
            Problem problem = new Problem(puzzle, puzzleSize);
        
            /*
            *   Executes BFS algorithm
            */
            if (selectedAlgorithm.equals("BFS")) {
                BreadthFirstSearch bfs = new BreadthFirstSearch(problem);
                bfs.search();
                String info = "solution : "+bfs.getSolution()+"\n\n"+
                              "nodes in frontier : "+bfs.getFrontierSize()+"\n\n"+
                              "moves : "+bfs.getNumberOfMoves()+"\n\n"+
                              "depth : "+bfs.getSolutionNodeDepth()+"\n\n"+
                              "time elapsed : "+bfs.getTimeElapsed()+" milliseconds\n\n"+
                              "memory used : "+bfs.getMemoryUsed()+" bytes\n\n"+
                              "explored nodes : "+bfs.getExplorados();
                jTextAreaInfo.setText(info);
                System.out.println(info);
            }
            
            /*
            *   Executes DFS algorithm
            */
            if (selectedAlgorithm.equals("DFS")) {
                DepthFirstSearch dfs = new DepthFirstSearch(problem);
                dfs.search();
                String info = "solution : "+dfs.getSolution()+"\n\n"+
                              "nodes in frontier : "+dfs.getFrontierSize()+"\n\n"+
                              "moves : "+dfs.getNumberOfMoves()+"\n\n"+
                              "depth : "+dfs.getSolutionNodeDepth()+"\n\n"+
                              "time elapsed : "+dfs.getTimeElapsed()+" milliseconds\n\n"+
                              "memory used : "+dfs.getMemoryUsed()+" bytes\n\n"+
                              "explored nodes : "+dfs.getExplorados();
                jTextAreaInfo.setText(info);
                System.out.println(info);
            }

            /*
            *   Executes A* algorithm with the manhattan distance heuristic
            */
            if (selectedAlgorithm.equals("A* Manhattan")) {
                AStar astar = new AStar(problem);
                astar.searchWithManhattanDistance();
                String info = "solution : "+astar.getSolution()+"\n\n"+
                              "nodes in frontier : "+astar.getFrontierSize()+"\n\n"+
                              "moves : "+astar.getNumberOfMoves()+"\n\n"+
                              "depth : "+astar.getSolutionNodeDepth()+"\n\n"+
                              "time elapsed : "+astar.getTimeElapsed()+" milliseconds\n\n"+
                              "memory used : "+astar.getMemoryUsed()+" bytes\n\n"+
                              "explored nodes : "+astar.getExplorados();
                jTextAreaInfo.setText(info);
                System.out.println(info);
            }

            /*
            *   Executes A* algorithm with the missplaced tiles heuristic
            */
            if (selectedAlgorithm.equals("A* Missplaced")) {
                AStar astar = new AStar(problem);
                astar.searchWithMissplacedTiles();
                String info = "solution : "+astar.getSolution()+"\n\n"+
                              "nodes in frontier : "+astar.getFrontierSize()+"\n\n"+
                              "moves : "+astar.getNumberOfMoves()+"\n\n"+
                              "depth : "+astar.getSolutionNodeDepth()+"\n\n"+
                              "time elapsed : "+astar.getTimeElapsed()+" milliseconds\n\n"+
                              "memory used : "+astar.getMemoryUsed()+" bytes\n\n"+
                              "explored nodes : "+astar.getExplorados();
                jTextAreaInfo.setText(info);
                System.out.println(info);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jPanel_container, "Juego no valido, revisar!");
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jRadioButtonMenuItem_3by3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem_3by3ActionPerformed
        puzzleSize = 3;
        jPanel_puzzle.removeAll();
        jPanel_puzzle.add(jPanel_3by3Puzzle);
        jPanel_puzzle.repaint();
        jPanel_puzzle.revalidate();
    }//GEN-LAST:event_jRadioButtonMenuItem_3by3ActionPerformed

    private void jRadioButtonMenuItem_BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem_BFSActionPerformed
        jButtonSearch.setText("Search "+algorithmsGroup.getSelection().getActionCommand()+" !");
    }//GEN-LAST:event_jRadioButtonMenuItem_BFSActionPerformed

    private void jRadioButtonMenuItem_manhattanDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem_manhattanDistanceActionPerformed
        jButtonSearch.setText("Search "+algorithmsGroup.getSelection().getActionCommand()+" !");
    }//GEN-LAST:event_jRadioButtonMenuItem_manhattanDistanceActionPerformed

    private void jRadioButtonMenuItem_missplacedTilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem_missplacedTilesActionPerformed
        jButtonSearch.setText("Search "+algorithmsGroup.getSelection().getActionCommand()+" !");
    }//GEN-LAST:event_jRadioButtonMenuItem_missplacedTilesActionPerformed

    private void jRadioButtonMenuItem_4by4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem_4by4ActionPerformed
        puzzleSize = 4;
        jPanel_puzzle.removeAll();
        jPanel_puzzle.add(jPanel_4by4Puzzle);
        jPanel_puzzle.repaint();
        jPanel_puzzle.revalidate();      
    }//GEN-LAST:event_jRadioButtonMenuItem_4by4ActionPerformed

    private void jMenuItem_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_aboutActionPerformed
        JOptionPane.showMessageDialog(jPanel_container, "Desarrollado por\n"
                + "Alumno : Luis Eduardo Vela Ruiz\n"
                + "No. control : 13041433\n"
                + "Materia : Inteligencia Artificial");
    }//GEN-LAST:event_jMenuItem_aboutActionPerformed
 
    private void generatePuzzle(){
        switch(puzzleSize){
            case 3:
                    puzzle = new byte[puzzleSize][puzzleSize];
                    puzzle[0][0] =  Byte.valueOf( jTextField_3tile_0.getText() );
                    puzzle[0][1] =  Byte.valueOf( jTextField_3tile_1.getText() );
                    puzzle[0][2] =  Byte.valueOf( jTextField_3tile_2.getText() );
                    puzzle[1][0] =  Byte.valueOf( jTextField_3tile_3.getText() );
                    puzzle[1][1] =  Byte.valueOf( jTextField_3tile_4.getText() );
                    puzzle[1][2] =  Byte.valueOf( jTextField_3tile_5.getText() );
                    puzzle[2][0] =  Byte.valueOf( jTextField_3tile_6.getText() );
                    puzzle[2][1] =  Byte.valueOf( jTextField_3tile_7.getText() );
                    puzzle[2][2] =  Byte.valueOf( jTextField_3tile_8.getText() );
                break;
            case 4:
                    puzzle = new byte[puzzleSize][puzzleSize];
                    puzzle[0][0] = Byte.valueOf( jTextField_4tile_0.getText() );
                    puzzle[0][1] = Byte.valueOf( jTextField_4tile_1.getText() );
                    puzzle[0][2] = Byte.valueOf( jTextField_4tile_2.getText() );
                    puzzle[0][3] = Byte.valueOf( jTextField_4tile_3.getText() );
                    puzzle[1][0] = Byte.valueOf( jTextField_4tile_4.getText() );
                    puzzle[1][1] = Byte.valueOf( jTextField_4tile_5.getText() );
                    puzzle[1][2] = Byte.valueOf( jTextField_4tile_6.getText() );
                    puzzle[1][3] = Byte.valueOf( jTextField_4tile_7.getText() );
                    puzzle[2][0] = Byte.valueOf( jTextField_4tile_8.getText() );
                    puzzle[2][1] = Byte.valueOf( jTextField_4tile_9.getText() );
                    puzzle[2][2] = Byte.valueOf( jTextField_4tile_10.getText() );
                    puzzle[2][3] = Byte.valueOf( jTextField_4tile_11.getText() );
                    puzzle[3][0] = Byte.valueOf( jTextField_4tile_12.getText() );
                    puzzle[3][1] = Byte.valueOf( jTextField_4tile_13.getText() );
                    puzzle[3][2] = Byte.valueOf( jTextField_4tile_14.getText() );
                    puzzle[3][3] = Byte.valueOf( jTextField_4tile_15.getText() );
                break;
        }
    }//end generatePuzzle
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }//end main

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup algorithmsGroup;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_about;
    private javax.swing.JMenu jMenu_AStar;
    private javax.swing.JMenu jMenu_configureAlgorithm;
    private javax.swing.JMenu jMenu_puzzleSize;
    private javax.swing.JMenu jMenu_settings;
    private javax.swing.JPanel jPanel_3by3Puzzle;
    private javax.swing.JPanel jPanel_4by4Puzzle;
    private javax.swing.JPanel jPanel_container;
    private javax.swing.JPanel jPanel_info;
    private javax.swing.JPanel jPanel_puzzle;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_3by3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_4by4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_BFS;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_DFS;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_manhattanDistance;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem_missplacedTiles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextAreaInfo;
    private javax.swing.JTextField jTextField_3tile_0;
    private javax.swing.JTextField jTextField_3tile_1;
    private javax.swing.JTextField jTextField_3tile_2;
    private javax.swing.JTextField jTextField_3tile_3;
    private javax.swing.JTextField jTextField_3tile_4;
    private javax.swing.JTextField jTextField_3tile_5;
    private javax.swing.JTextField jTextField_3tile_6;
    private javax.swing.JTextField jTextField_3tile_7;
    private javax.swing.JTextField jTextField_3tile_8;
    private javax.swing.JTextField jTextField_4tile_0;
    private javax.swing.JTextField jTextField_4tile_1;
    private javax.swing.JTextField jTextField_4tile_10;
    private javax.swing.JTextField jTextField_4tile_11;
    private javax.swing.JTextField jTextField_4tile_12;
    private javax.swing.JTextField jTextField_4tile_13;
    private javax.swing.JTextField jTextField_4tile_14;
    private javax.swing.JTextField jTextField_4tile_15;
    private javax.swing.JTextField jTextField_4tile_2;
    private javax.swing.JTextField jTextField_4tile_3;
    private javax.swing.JTextField jTextField_4tile_4;
    private javax.swing.JTextField jTextField_4tile_5;
    private javax.swing.JTextField jTextField_4tile_6;
    private javax.swing.JTextField jTextField_4tile_7;
    private javax.swing.JTextField jTextField_4tile_8;
    private javax.swing.JTextField jTextField_4tile_9;
    private javax.swing.ButtonGroup puzzleSizeGroup;
    // End of variables declaration//GEN-END:variables
}//end class